bind = "0.0.0.0:25567"
accept_transfers = true
fetch_player_skins = false

[forwarding]
method = "NONE"

[version_gate]
protocol = 769
version = "1.21.4"
min_protocol = 768
min_version_name = "1.21"
max_protocol = 0
max_version_name = ""
kick_message = "§6» §e» §6§lDYNASTIA §e« §6«\n\n§cLe serveur accepte uniquement les versions §6<range>§c."

[upstream]
status_addr = "10.99.0.2:25568"
poll_secs = 10
transfer_host = "play.dynastia.fr"
transfer_port = 25568
retry_secs = 5
